#
# ███╗░░░███╗██████╗░░█████╗░██████╗░██████╗░███████╗██████╗░
# ████╗░████║██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ██╔████╔██║██████╦╝██║░░██║██████╔╝██║░░██║█████╗░░██████╔╝
# ██║╚██╔╝██║██╔══██╗██║░░██║██╔══██╗██║░░██║██╔══╝░░██╔══██╗
# ██║░╚═╝░██║██████╦╝╚█████╔╝██║░░██║██████╔╝███████╗██║░░██║
# ╚═╝░░░░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝
#
#        A plugin that will mimic the mechanics of the
#    Minehut server "Wife"'s WorldBorder (wife.minehut.gg)
#

enabled: true
# Set this value to 'false' if you want the plugin to disable itself upon starting up
# NOTE: This requires a restart to take effect

worldBorderSize: 100.0
# The size the WorldBorder will constantly be at

worldBorderColor: BLUE
# The color of the WorldBorder, possible colors are 'RED', 'BLUE', and 'GREEN'

worldBorderAnimal: PIG
# The mob that will be in the middle of the WorldBorder

worldBorderAnimalName: '&b&lWorldBorder Center'
# The name of the mob at the center, set to 'empty' to remain none

worldBorderAnimalGlowing: true
# Determines if the WorldBorder animal will glow or not

worldBorderAnimalSilent: true
# Determines if the WorldBorder animal is silent or not

updateWorldBorderInterval: 5
# How long the WorldBorder gets the location of the animal and sets worldborder
# accordingly. This value is in ticks (20 ticks = 1 second), cannot go below 1.

persistent: true
# Determines if the WorldBorder location, enabled status, etc. will be persistent
# through restarts and server shut-downs




configVersion: 1.0.0
# Do not change!!!!!