#
# ███╗░░░███╗██████╗░░█████╗░██████╗░██████╗░███████╗██████╗░
# ████╗░████║██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ██╔████╔██║██████╦╝██║░░██║██████╔╝██║░░██║█████╗░░██████╔╝
# ██║╚██╔╝██║██╔══██╗██║░░██║██╔══██╗██║░░██║██╔══╝░░██╔══██╗
# ██║░╚═╝░██║██████╦╝╚█████╔╝██║░░██║██████╔╝███████╗██║░░██║
# ╚═╝░░░░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝
#
#        A plugin that will mimic the mechanics of the
#    Minehut server "Wife"'s WorldBorder (wife.minehut.gg)
#

enabled: true
# Set this value to 'false' if you want the plugin to disable itself upon starting up
# NOTE #1: This just disables the plugin and will not reset the WorldBorder, kill the pig
#          or do anything along those lines. This isn't really meant to be used to be honest.
# NOTE #2: This requires a restart to take effect

overworld:
  worldBorderSize: 100.0
  # The size the WorldBorder will constantly be at

  worldBorderColor: BLUE
  # The color of the WorldBorder, possible colors are 'RED', 'BLUE', and 'GREEN'

  worldBorderDamage: 0.0
  # How much damage the WorldBorder does per block outside the border, and then the one
  # below controls how far out of the border you need to go in order to start taking damage
  # (a.k.a. the 'buffer')
  worldBorderBuffer: 0.0

  worldBorderTeleport: 50.0
  # How many blocks outside the WorldBorder you must be to get teleported back to safety

  worldBorderAnimal: PIG
  # The mob that will be in the middle of the WorldBorder

  worldBorderAnimalName: '&aOverworld &b&lWorldBorder'
  # The name of the mob at the center, set to 'empty' to remain none

  worldBorderAnimalGlowing: true
  # Determines if the WorldBorder animal will glow or not

  worldBorderAnimalSilent: true
  # Determines if the WorldBorder animal is silent or not

nether:
  worldBorderSize: 100.0
  # The size the WorldBorder will constantly be at

  worldBorderColor: RED
  # The color of the WorldBorder, possible colors are 'RED', 'BLUE', and 'GREEN'

  worldBorderDamage: 0.0
  # How much damage the WorldBorder does per block outside the border, and then the one
  # below controls how far out of the border you need to go in order to start taking damage
  # (a.k.a. the 'buffer')
  worldBorderBuffer: 0.0

  worldBorderTeleport: 50.0
  # How many blocks outside the WorldBorder you must be to get teleported back to safety

  worldBorderAnimal: STRIDER
  # The mob that will be in the middle of the WorldBorder

  worldBorderAnimalName: '&cNether &b&lWorldBorder'
  # The name of the mob at the center, set to 'empty' to remain none

  worldBorderAnimalGlowing: true
  # Determines if the WorldBorder animal will glow or not

  worldBorderAnimalSilent: true
  # Determines if the WorldBorder animal is silent or not

updateWorldBorderInterval: 1
# How long the WorldBorder gets the location of the animal and sets worldborder
# accordingly. This value is in ticks (20 ticks = 1 second), cannot go below 1.

msgOnRespawn: CHAT
# Determines if the server will send a message/title to the server if the mob has
# died and is attempting to respawn it.
# Possible options: CHAT, TITLE, BOSSBAR, ACTIONBAR

persistent: false
# Determines if the WorldBorder location, enabled status, etc. will be persistent
# through restarts and server shut-downs




configVersion: 1.0.0
# Do not change!!!!!