name: MBorder
version: ${project.version}
main: net.cybercake.mborder.Main
api-version: 1.17
authors: [ CyberedCake ]
description: A recreation of the Minehut server "Wife"'s moving border mechanics
website: https://github.com/CyberedCake/MBorder

permissions:
  mborder.*:
    description: Allowing a player this permission will give them all permissions for the MBorder plugin
    children:
      - mborder.command.reload: true
      - mborder.command.coordscheck: true
      - mborder.command.toggleactive: true
      - mborder.command.tpmob: true
      - mborder.command.nextautorespawn: true
  mborder.command.reload:
    description: Allowing a player this permission will give them the ability to use /mborder reload
    default: op
  mborder.command.coordscheck:
    description: Allowing a player this permission will give them the ability to use /mborder coordscheck
    default: not op
  mborder.command.toggleactive:
    description: Allowing a player this permission will give them the ability to use /mborder toggleactive
    default: op
  mborder.command.tpmob:
    description: Allowing a player this permission will give them the ability to use /mborder tpmob
    default: op
  mborder.command.nextautorespawn:
    description: Allowing a player this permission will give them the ability to use /mborder nextautorespawn
    default: not op

commands:
  mborder:
    description: The main command for the plugin MBorder
    usage: Use /mborder help for help!
    aliases: [movingborder, mb]