name: MBorder
version: ${project.version}
main: net.cybercake.mborder.Main
api-version: 1.17
authors: [ CyberedCake ]
description: A recreation of the Minehut server "Wife"'s moving border mechanics
website: https://github.com/CyberedCake/MBorder

permissions:
  mborder.*:
    description: Allowing a player this permission will give them all permissions for the MBorder plugin
    default: op
    children:
      - mborder.command.reload
      - mborder.command.distancebetween
      - mborder.command.toggleactive
  mborder.command.reload:
    description: Allowing a player this permission will give them the ability to use /mborder reload
    default: op
  mborder.command.distancebetween:
    description: Allowing a player this permission will give them the ability to use /mborder distancebetween
    default: op
  mborder.command.toggleactive:
    description: Allowing a player this permission will give them the ability to use /mborder toggleactive
    default: op

commands:
  mborder:
    description: The main command for the plugin MBorder
    usage: Use /mborder help for help!
    aliases: [movingborder, mb]